#!/usr/bin/env node
// -*- mode: js -*-

var fs = require('fs');
var dtp = require('dtrace-provider').createDTraceProvider('nodecat');

dtp.addProbe('fs-read-start', 'char *', 'char *');
dtp.addProbe('fs-read-done', 'char *', 'int');
function readFile(file) {
    dtp.fire('fs-read-start', function () {
        return [file]
    });

    return fs.readFile(file, 'utf8', function (err, data) {
        dtp.fire('fs-read-done', function () {
            return [file, err ? err.code : null, data ? data.length : 0];
        });
        if (err)
            throw err;

        console.log(data);
    });
}

dtp.enable();
process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', function (data) {
    process.stdin.pause();
    process.argv.slice(2).forEach(function (f) {
        return readFile(f);
    });
});
process.stderr.write('> ');



